### PR TITLE
Pump, Rotor recipe tweaks

### PR DESCRIPTION
**Pull request by pyure**
* Pump now requires plates instead of tools
* Rotor now requires 1 tool instead of 3
* Reduced amount of soldering fluid required in assembler 
* Doubled pump extraction rate

### CODE REVIEW

**Comment by Archengius** [comment]
Remove soldering fluid requirement completely, also remove screw from assembler recipe.

**Comment by Agrax** [comment]
> 
> 
> Remove soldering fluid requirement completely, also remove screw from assembler recipe.

I agree on the screw. It's kind of obsolete. Assembler should make the recipe simpler, but i'd insist on the soldering material, as in the assembler it traditionally replaces all these screws and other fiddly bits and pieces. But hey! Im just a rando from the internet! Why would anyone listen to the humble me?

**Comment by pyure** [comment]
PR changes done.

**Comment by Agrax** [comment]
Looks bad :[

**Comment by pyure** [comment]
Looks/feels good to me.

**Comment by Agrax** [comment]
Well... One of us has bad taste

**Pull request merged**
