### PR TITLE
Improved number formatting, with a couple of other fixes

### PR DESCRIPTION
**Pull request by warjort**
**What:**
Improved number formatting to include thousands seperators according to locale.

**How solved:**
Changed %d in the language file to %,d

**Outcome:**
Does some of #1323

**Additional info:**
While doing this I discovered a few places where %d was used when it should have been using %s or %f

I also found that the code for slot widget in the crafting table used gregtech.item_list.item_stored while the language file was gregtech.item_list.items_stored, I changed the language file.

There are some places like the multiblock boiler or the gt util hand command that use minecraft's TextComponentTransalation api. This doesn't work with %,d so I didn't change these. Other places that use this api in the code, format numbers using %s.

I haven't touched the russian or chinese translations. They will not have the thousands seperators until somebody that speaks those languages does the same excercise.

**Possible compatibility issue:**
If one of the addon mods is reusing some of these translations, it may break their display if they have the same misuse as the %s and %f issue I fixed.

### CODE REVIEW

**Comment by warjort** [comment]
One other change I did inadvertantly but decided to keep for the purposes of comment is that the GT tools attack damage and digging speed now show the first decimal. e.g. before it might show Attack Damage: 7, now it will show Attack Damage: 7.2

I don't know if the decimals are actually used by minecraft?

**Comment by LAGIdiot** [comment]
I have tagged this as open for discussion. As I would like to hear opinion of others. Please don't turn this to hate fest...

@warjort also don't leave comments of what was changed to what in code we can see that from git history

**Comment by warjort** [comment]
> @warjort also don't leave comments of what was changed to what in code we can see that from git history
But translators don't necessarily know how to read git diffs. The ==> is for them.

**Comment by warjort** [comment]
Take a look at #1484 if you want to see what the %,d looks like.

**Comment by LAGIdiot** [comment]
We are not using any translator services. So knowledge how to use git is required. Which means they should be able to use diff too.

**Comment by LAGIdiot** [comment]
I am pinging this one from Discord so we can get discussion going

**Pull request merged**
