### PR TITLE
Allow covers on chest bottoms

### PR DESCRIPTION
**Pull request by htmlcsjs**
**What:**
This solved the issue of covers not being able to put on chest bottoms. 

**How solved:**
This is solved by changing the hitbox and rendering box of gt chests so a cover can fit on with a plate.

**Outcome:**
Fixes: #1312

**Additional info:**
covers on chest
Screenshot_20210422_174411

**Possible compatibility issue:**
Hitbox changes, could mess with texture packs. I also changes base textures to accommodate the hitbox change

### CODE REVIEW

**Comment by million09** [comment]
How about front face too? We can put covers on front face by rotating the chest, but not directly.

**Comment by htmlcsjs** [comment]
You can by rotating the chest with a wrench: see here https://i.neeve.co/VioletUnlinedEft.mp4

**Comment by LAGIdiot** [comment]
This is more about ideology then technical implementation and right now I don't know what to do with it. We should probably discuss this on Discord.

**Comment by LAGIdiot** [comment]
GTCE council reviewed this and come to conclusion that chests should allow covers on bottom side. So this does not go against our principles thus this is acceptable and can be reviewed.

**Review by LAGIdiot — APPROVED** [review]

**Pull request merged**
