### PR TITLE
Improvement/update dependencies to last version

### PR DESCRIPTION
**Pull request by LAGIdiot**
All dependencies were updated to latest/last official version available
(last is really meant as LAST because most of them did not get update in years)

Forge updated to 14.23.5.2847

CraftTweaker updated to 4.1.9.6
CodeChickenLib updated to 3.2.3.358
Forestry updated to 5.8.2.387
ForgeMultipart updated to 2.6.2.83
JEI updated to 4.15.0.291
The One Probe updated to 1.4.28

Bump version

### CODE REVIEW

**Comment by huneau** [comment]
The One Probe updated to 1.4.28
this version seems buggy. 
on my side, I have issue with `GregtechTileCapabilities.CAPABILITY_CONTROLLABLE.cast(this);` (or other capabilities) when TOP ask info

**Comment by LAGIdiot** [comment]
I have retest it again and I don't see any problems on GTCE side. There are no errors in logs, no exceptions what so ever. And all info provides for TOP works correctly.

Are you sure you are using it correctly in your code?

**Comment by huneau** [comment]
unknown
The issue is probably not TOP but I see a lot of issue like that... and it's not particularly mine

**Comment by LAGIdiot** [comment]
It seems that issue must be in how _topaddons:ic2_ or _gtadditions:screwdriver_provider_ works, maybe both or block you are looking at. But either way this is **not** GTCE problem. This version of TOP exists for more then year so it is kind of theirs problem that they did not adapt yet.

**Comment by huneau** [comment]
I made some testing and the issue is not in TOP... its somewhere near `GregtechTileCapabilities.CAPABILITY_CONTROLLABLE.cast(this);` 
my side, I dont use that because it doesn't work I do `(T) this`
exactly the same but .......................

**Comment by huneau** [comment]
the codechicken lib is a real pain, the repo doesnt work I have to add another one

**Comment by huneau** [comment]
@pyure I tested the branch of @LAGIdiot I dont see issue, seems fine for me

**Pull request merged**
