### PR TITLE
Allow for filling and emptying Fluid Hatches through the GUI

### PR DESCRIPTION
**Pull request by fmarceau**
**What:**
Based on #1277, this PR allows for filling and emptying Fluid Hatches.

**How solved:**
The TankWidget which Fluid Hatches are relying on already has that feature, I only had to enable it.

**Outcome:**
Closes #1227 

**Additional info:**
Please note that it is not allowed to fill an Output Fluid Hatch with a fluid container, only input hatches are supported to that regard.

### CODE REVIEW

**Comment by LAGIdiot** [comment]
I had quite different idea about how this should be implemented. I was thinking about using `FluidContainerSlotWidget` to accept empty container and put fluids to it as it does for Export Hatch.

Even if your implementation is interesting I would rather not change feel for this block. And also it would not be obvious for players that `TankWidget` is clickable.

**Comment by fmarceau** [comment]
> I had quite different idea about how this should be implemented. I was thinking about using `FluidContainerSlotWidget` to accept empty container and put fluids to it as it does for Export Hatch.
> 
> Even if your implementation is interesting I would rather not change feel for this block. And also it would not be obvious for players that `TankWidget` is clickable.

Ok, I will see what I can do to adapt it.

**Comment by LAGIdiot** [comment]
Are you still looking at this? Do you need some help with it?

**Comment by LAGIdiot** [comment]
Closing this as stale

**Pull request closed without merging**
