### PR TITLE
Allow walking over surface rocks #1455

### LINKED ISSUE #1455: [Suggestion] Allow walking over surface rocks
**Is your feature request related to a problem? Please describe.**
It is annoying you have jump to get over the indicator surface rocks.

**Describe the solution you'd like**
Change the bounding box to be half a block tall, like a slab.
````
diff --git a/src/main/java/gregtech/common/blocks/surfacerock/BlockSurfaceRock.java b/src/main/java/gregtech/common/blocks/surfacerock/BlockSurfaceRock.java
old mode 100644
new mode 100755
index dcd9ec68..267c0089
--- a/src/main/java/gregtech/common/blocks/surfacerock/BlockSurfaceRock.java
+++ b/src/main/java/gregtech/common/blocks/surfacerock/BlockSurfaceRock.java
@@ -25,7 +25,7 @@ import java.util.Random;
 
 public abstract class BlockSurfaceRock extends Block {
 
-    private static final AxisAlignedBB STONE_AABB = new AxisAlignedBB(0.0, 0.0, 0.0, 1.0, 12.0 / 16.0, 1.0);
+    private static final AxisAlignedBB STONE_AABB = new AxisAlignedBB(0.0, 0.0, 0.0, 1.0, 8.0 / 16.0, 1.0);
 
     public BlockSurfaceRock() {
         super(net.minecraft.block.material.Material.ROCK);
````

**Additional context**
The current bounding box is .75 of a block which is greater than the .6 limit for having to jump.
If you look at the gregtech.common.render.StonePileModelGenerator, the actual size of the stone piles is between 4/16 and 7/16 of a block.
````
            int stoneHeight = 4 + random.nextInt(4);
````

### PR DESCRIPTION
**Pull request by warjort**
**What:**
Allow walking over surface rocks.

**How solved:**
Changed the surface rock bounding box to be half a block tall.

**Outcome:**
Closes #1455

### CODE REVIEW

**Review by LAGIdiot — APPROVED** [review]
Thanks for making it to PR.

**Comment by ALongStringOfNumbers** [comment]
Is this small enough for mobs to be able to walk over? If so, it might need to override `isPassable` to prevent mob AI issues where they spin in circles attempting to pathfind.

**Comment by warjort** [comment]
> Is this small enough for mobs to be able to walk over?

I believe they use the same limit as players?

> to prevent mob AI issues where they spin in circles attempting to pathfind.

Wouldn't that help to find ores? :-)

**Comment by LAGIdiot** [comment]
@warjort Can you please test it so we can dismiss or fix @ALongStringOfNumbers concerns.

**Comment by warjort** [comment]
I can change it to not be passable by mobs as suggested. But this is no different to a cable or any other block an entity can walk over.

My understanding is that the spinning comes the opposite type of block like fences? 
i.e. blocks that mobs can stand on top of, but normally wouldn't be able to jump directly onto.

**Comment by LAGIdiot** [comment]
Can you just get some monsters spawned take them over surface rocks and if they are not spinning we are good and if they are then some fix has to be introduced?

**Comment by warjort** [comment]
Why? In the last couple of months I have commited a number real changes/fixes to the repository that go unreviewed.

But all you are worried about is non functional stuff like inadvertant white space changes, comments that in your opinion are unhelpful, and this non-problem.

If it is a problem, it is a problem for at least 30 other existing blocks in this mod.

Instead you want to me sit there spawning mobs trying to prove a negative. 
How many mobs do I need to spawn, 10? Maybe the 11th will spin.

**Comment by warjort** [comment]
And by the way changing isPassable() to false will just make the mobs think it is a full block. 
They will still be able to jump on top of it.

**Comment by LAGIdiot** [comment]
I am sorry if my comment made you angry. I was trying to satisfy concern of other participating member.
I am trying my best to manage current load of tasks to attend. I am aware that there are bigger things that needs my attention and you are not only one who is waiting for me.
But one thing is comment here which takes me minutes and I can do it from everywhere and other thing is spinning my dev environment and diving deep to some difficult mechanics.

If you feel you can do better than me, then feel free to contact project owner with request to replace me. And if he agrees I will gladly step down, because I want best for GTCE.

**Comment by warjort** [comment]
I am not trying to usurp your place, I would not want to.
I am trying to fix bugs.
I understand you are busy, but making nonfunctional changes just wastes my time as well.

**Pull request merged**
