### PR TITLE
[WIP] Delete converting 8 Wheat into Plant Balls recipe

### LINKED ISSUE #1487: [BUG] Conflicting recipes for wheat in Compressor
**Describe the bug**
It's impossible to get a Hay Bale via Compressor while there are plenty recipes to get Plant Balls.
Original issue: https://github.com/TheLimePixel/GregBlock/issues/230

**Versions**
Forge: 14.23.5.2847
GTCE: 1.11.3

**Setup**
Playing Solo

**Steps To Reproduce**
1) For this bug we will need 64 Wheat, Basic Compressor, Basic Diesel Generator, Diesel Bucket (any)
2) Place generator, connect compressor to it
3) Put all Wheat in Compressor
4) Put Diesel in Generator
5) See that you are getting Plant Ball

**Expected behavior**
It is possible to craft Hay Bale automatically in compressors or maybe in packagers.

**Screenshots (JEI)**
image

### PR DESCRIPTION
**Pull request by CrafterKolyan**
**What:**
Deletes conflicting recipe (not the best variant maybe)

**Outcome:**
Fix #1487

### CODE REVIEW

**Comment by warjort** [comment]
This doesn't look right. 

You can make hay bales from wheat in the crafting table (vanilla recipe). 
While the compressor is the only route for making plant balls from wheat.

Also plant balls have a use in GT in making biomass, hay bales are mostly decorative.

Finally, you have deleted a recipe that works and could be automated in peoples worlds,
in favour of a recipe that nobody could be using?

**Comment by CrafterKolyan** [comment]
Well maybe it means we need to delete 9 wheat recipe or we will just leave it as is? In my opinion only one recipe should be shown in jei

**Comment by DStrand1** [comment]
Personally I think the 9 Wheat recipe should be either removed or moved to the Packager, since its not even possible to do this recipe currently.

**Comment by Exaxxion** [comment]
Rather than putting "[WIP]" in the title, GitHub has "draft" PRs that show others that you are working on a particular issue but it is not yet ready for code review and merging. You can [change this pull request into a draft PR](https://github.blog/changelog/2020-04-08-convert-pull-request-to-draft/), and you can convert it back into a standard PR when you are done.

**Comment by LAGIdiot** [comment]
I don't feel like giving up on converting Wheat to Plant Balls. So I suggest to move recipe for creating Hay Bale to Packager.

**Comment by MrEyeballs29** [comment]
I had to agree, plant balls are used for effective fuel, while hay bales
are used for decoration purposes.

**Pull request closed without merging**
